<javaelement>
	<package>
		java.security.cert
	</package>
	<type>
		<name>
			public class CertStoreException  extends GeneralSecurityException
		</name>
		<description>
			An exception indicating one of a variety of problems retrieving certificates and CRLs from a CertStore. A CertStoreException provides support for wrapping exceptions. The getCause method returns the throwable, if any, that caused this exception to be thrown. Concurrent Access Unless otherwise specified, the methods defined in this class are not thread-safe. Multiple threads that need to access a single object concurrently should synchronize amongst themselves and provide the necessary locking. Multiple threads each manipulating separate objects need not synchronize.
		</description>
		<methods>
			<method>
				<name>
					public CertStoreException()
				</name>
				<description>
					Creates a CertStoreException with null as its detail message.
				</description>
				
			</method>
			<method>
				<name>
					public CertStoreException(String msg)
				</name>
				<description>
					Creates a CertStoreException with the given detail message. A detail message is a String that describes this particular exception.
				</description>
				
			</method>
			<method>
				<name>
					public CertStoreException(Throwable cause)
				</name>
				<description>
					Creates a CertStoreException that wraps the specified throwable. This allows any exception to be converted into a CertStoreException, while retaining information about the cause, which may be useful for debugging. The detail message is set to (cause==null ? null : cause.toString()) (which typically contains the class and detail message of cause).
				</description>
				
			</method>
			<method>
				<name>
					public CertStoreException(String msg,                    Throwable cause)
				</name>
				<description>
					Creates a CertStoreException with the specified detail message and cause.
				</description>
				
			</method>
			
		</methods>
		
	</type>
	
</javaelement>
