<javaelement>
	<package>
		java.lang
	</package>
	<type>
		<name>
			public class ExceptionInInitializerError  extends LinkageError
		</name>
		<description>
			Signals that an unexpected exception has occurred in a static initializer. An ExceptionInInitializerError is thrown to indicate that an exception occurred during evaluation of a static initializer or the initializer for a static variable. As of release 1.4, this exception has been retrofitted to conform to the general purpose exception-chaining mechanism. The "saved throwable object" that may be provided at construction time and accessed via the getException() method is now known as the cause, and may be accessed via the Throwable.getCause() method, as well as the aforementioned "legacy method."
		</description>
		<methods>
			<method>
				<name>
					public ExceptionInInitializerError()
				</name>
				<description>
					Constructs an ExceptionInInitializerError with null as its detail message string and with no saved throwable object. A detail message is a String that describes this particular exception.
				</description>
				
			</method>
			<method>
				<name>
					public ExceptionInInitializerError(Throwable thrown)
				</name>
				<description>
					Constructs a new ExceptionInInitializerError class by saving a reference to the Throwable object thrown for later retrieval by the getException() method. The detail message string is set to null.
				</description>
				
			</method>
			<method>
				<name>
					public ExceptionInInitializerError(String s)
				</name>
				<description>
					Constructs an ExceptionInInitializerError with the specified detail message string. A detail message is a String that describes this particular exception. The detail message string is saved for later retrieval by the Throwable.getMessage() method. There is no saved throwable object.
				</description>
				
			</method>
			<method>
				<name>
					public Throwable getException()
				</name>
				<description>
					Returns the exception that occurred during a static initialization that caused this error to be created. This method predates the general-purpose exception chaining facility. The Throwable.getCause() method is now the preferred means of obtaining this information.
				</description>
				
			</method>
			<method>
				<name>
					public Throwable getCause()
				</name>
				<description>
					Returns the cause of this error (the exception that occurred during a static initialization that caused this error to be created).
				</description>
				
			</method>
			
		</methods>
		
	</type>
	
</javaelement>
