<javaelement>
	<package>
		java.rmi
	</package>
	<type>
		<name>
			public class RemoteException  extends IOException
		</name>
		<description>
			A RemoteException is the common superclass for a number of communication-related exceptions that may occur during the execution of a remote method call. Each method of a remote interface, an interface that extends java.rmi.Remote, must list RemoteException in its throws clause. As of release 1.4, this exception has been retrofitted to conform to the general purpose exception-chaining mechanism. The "wrapped remote exception" that may be provided at construction time and accessed via the public detail field is now known as the cause, and may be accessed via the Throwable.getCause() method, as well as the aforementioned "legacy field." Invoking the method Throwable.initCause(Throwable) on an instance of RemoteException always throws IllegalStateException.
		</description>
		<methods>
			<method>
				<name>
					public Throwable detail
				</name>
				<description>
					The cause of the remote exception. This field predates the general-purpose exception chaining facility. The Throwable.getCause() method is now the preferred means of obtaining this information.
				</description>
				
			</method>
			<method>
				<name>
					public RemoteException()
				</name>
				<description>
					Constructs a RemoteException.
				</description>
				
			</method>
			<method>
				<name>
					public RemoteException(String s)
				</name>
				<description>
					Constructs a RemoteException with the specified detail message.
				</description>
				
			</method>
			<method>
				<name>
					public RemoteException(String s,                 Throwable cause)
				</name>
				<description>
					Constructs a RemoteException with the specified detail message and cause. This constructor sets the detail field to the specified Throwable.
				</description>
				
			</method>
			<method>
				<name>
					public String getMessage()
				</name>
				<description>
					Returns the detail message, including the message from the cause, if any, of this exception.
				</description>
				
			</method>
			<method>
				<name>
					public Throwable getCause()
				</name>
				<description>
					Returns the cause of this exception. This method returns the value of the detail field.
				</description>
				
			</method>
			
		</methods>
		
	</type>
	
</javaelement>
