<javaelement>
	<package>
		javax.xml.soap
	</package>
	<type>
		<name>
			public class SOAPException  extends Exception
		</name>
		<description>
			An exception that signals that a SOAP exception has occurred. A SOAPException object may contain a String that gives the reason for the exception, an embedded Throwable object, or both. This class provides methods for retrieving reason messages and for retrieving the embedded Throwable object. Typical reasons for throwing a SOAPException object are problems such as difficulty setting a header, not being able to send a message, and not being able to get a connection with the provider. Reasons for embedding a Throwable object include problems such as input/output errors or a parsing problem, such as an error in parsing a header.
		</description>
		<methods>
			<method>
				<name>
					public SOAPException()
				</name>
				<description>
					Constructs a SOAPException object with no reason or embedded Throwable object.
				</description>
				
			</method>
			<method>
				<name>
					public SOAPException(String reason)
				</name>
				<description>
					Constructs a SOAPException object with the given String as the reason for the exception being thrown.
				</description>
				
			</method>
			<method>
				<name>
					public SOAPException(String reason,               Throwable cause)
				</name>
				<description>
					Constructs a SOAPException object with the given String as the reason for the exception being thrown and the given Throwable object as an embedded exception.
				</description>
				
			</method>
			<method>
				<name>
					public SOAPException(Throwable cause)
				</name>
				<description>
					Constructs a SOAPException object initialized with the given Throwable object.
				</description>
				
			</method>
			<method>
				<name>
					public String getMessage()
				</name>
				<description>
					Returns the detail message for this SOAPException object. If there is an embedded Throwable object, and if the SOAPException object has no detail message of its own, this method will return the detail message from the embedded Throwable object.
				</description>
				
			</method>
			<method>
				<name>
					public Throwable getCause()
				</name>
				<description>
					Returns the Throwable object embedded in this SOAPException if there is one. Otherwise, this method returns null.
				</description>
				
			</method>
			<method>
				<name>
					public Throwable initCause(Throwable cause)
				</name>
				<description>
					Initializes the cause field of this SOAPException object with the given Throwable object. This method can be called at most once. It is generally called from within the constructor or immediately after the constructor has returned a new SOAPException object. If this SOAPException object was created with the constructor SOAPException(Throwable) or SOAPException(String,Throwable), meaning that its cause field already has a value, this method cannot be called even once.
				</description>
				
			</method>
			
		</methods>
		
	</type>
	
</javaelement>
