<javaelement>
	<package>
		javax.activity
	</package>
	<type>
		<name>
			public class ActivityCompletedException  extends RemoteException
		</name>
		<description>
			This exception may be thrown on any method for which Activity context is accessed and indicates that ongoing work within the Activity is not possible. This may be because the Activity has been instructed to complete with CompletionStatusFailOnly or has ended as a result of a timeout. This exception will be propagated across ORB boundaries via an org.omg.CORBA.ACTIVITY_COMPLETED system exception. An application should handle this error by attempting to complete the Activity.
		</description>
		<methods>
			<method>
				<name>
					public ActivityCompletedException()
				</name>
				<description>
					Constructs a new instance with null as its detail message.
				</description>
				
			</method>
			<method>
				<name>
					public ActivityCompletedException(String message)
				</name>
				<description>
					Constructs a new instance with the specified detail message.
				</description>
				
			</method>
			<method>
				<name>
					public ActivityCompletedException(Throwable cause)
				</name>
				<description>
					Constructs a new throwable with the specified cause.
				</description>
				
			</method>
			<method>
				<name>
					public ActivityCompletedException(String message,                            Throwable cause)
				</name>
				<description>
					Constructs a new throwable with the specified detail message and cause.
				</description>
				
			</method>
			
		</methods>
		
	</type>
	
</javaelement>
