<javaelement>
	<package>
		javax.xml.crypto
	</package>
	<type>
		<name>
			public class URIReferenceException  extends Exception
		</name>
		<description>
			Indicates an exceptional condition thrown while dereferencing a URIReference. A URIReferenceException can contain a cause: another throwable that caused this URIReferenceException to get thrown.
		</description>
		<methods>
			<method>
				<name>
					public URIReferenceException()
				</name>
				<description>
					Constructs a new URIReferenceException with null as its detail message.
				</description>
				
			</method>
			<method>
				<name>
					public URIReferenceException(String message)
				</name>
				<description>
					Constructs a new URIReferenceException with the specified detail message.
				</description>
				
			</method>
			<method>
				<name>
					public URIReferenceException(String message,                       Throwable cause)
				</name>
				<description>
					Constructs a new URIReferenceException with the specified detail message and cause. Note that the detail message associated with cause is not automatically incorporated in this exception's detail message.
				</description>
				
			</method>
			<method>
				<name>
					public URIReferenceException(String message,                       Throwable cause,                       URIReference uriReference)
				</name>
				<description>
					Constructs a new URIReferenceException with the specified detail message, cause and URIReference. Note that the detail message associated with cause is not automatically incorporated in this exception's detail message.
				</description>
				
			</method>
			<method>
				<name>
					public URIReferenceException(Throwable cause)
				</name>
				<description>
					Constructs a new URIReferenceException with the specified cause and a detail message of (cause==null ? null : cause.toString()) (which typically contains the class and detail message of cause).
				</description>
				
			</method>
			<method>
				<name>
					public URIReference getURIReference()
				</name>
				<description>
					Returns the URIReference that was being dereferenced when the exception was thrown.
				</description>
				
			</method>
			<method>
				<name>
					public Throwable getCause()
				</name>
				<description>
					Returns the cause of this URIReferenceException or null if the cause is nonexistent or unknown. (The cause is the throwable that caused this URIReferenceException to get thrown.)
				</description>
				
			</method>
			<method>
				<name>
					public void printStackTrace()
				</name>
				<description>
					Prints this URIReferenceException, its backtrace and the cause's backtrace to the standard error stream.
				</description>
				
			</method>
			<method>
				<name>
					public void printStackTrace(PrintStream s)
				</name>
				<description>
					Prints this URIReferenceException, its backtrace and the cause's backtrace to the specified print stream.
				</description>
				
			</method>
			<method>
				<name>
					public void printStackTrace(PrintWriter s)
				</name>
				<description>
					Prints this URIReferenceException, its backtrace and the cause's backtrace to the specified print writer.
				</description>
				
			</method>
			
		</methods>
		
	</type>
	
</javaelement>
